name = "securemycameras"
main = "src/worker.ts"
compatibility_date = "2026-03-18"

[assets]
directory = "./dist"
binding = "ASSETS"

[[r2_buckets]]
binding = "PRIVATE_FILES"
bucket_name = "securemycameras-files"

[[kv_namespaces]]
binding = "PURCHASE_RECORDS"
id = "93ba5e33480f425489910bf0dddb2052"

[vars]
SUPPORT_EMAIL = "inquiry@salishsecurity.ai"
PRODUCT_NAME = "Secure Camera Setup Guide"
PADDLE_ENV = "sandbox"
RESEND_FROM = "Secure My Cameras <orders@salishsecurity.ai>"
