name = "securemycameras"
compatibility_date = "2026-03-18"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "./dist"

[[r2_buckets]]
binding = "PRIVATE_FILES"
bucket_name = "securemycameras-files"

[vars]
SUPPORT_EMAIL = "inquiry@salishsecurity.ai"
PRODUCT_NAME = "Secure Camera Setup Guide"
